### PR TITLE
add module selection configuration

### PR DESCRIPTION
**Pull request by luismoramedina**
Hi guikeller, when i have 2 or more webapp modules in the same intellij project, jetty runner creates the classpath based on all the project modules. So, if i have a duplicated resource (for example an application.properties) in those webapp modules there is a conflict.

I have commited a basic module configuration in my fork (branch module-selection-configuration). Please, check it and merge it if you think is helpful for other developers... or ask me for modifications if something is wrong.

Thanks in advance and great job!

### CODE REVIEW

**Comment by guikeller** [comment]
Hi @luismoramedina ,

Thanks a lot for your contribution and I think that if you need this feature others may need it too.

There is a couple of that I would like to discuss though:
1) On the UI we have to indicate whether that is a mandatory or optional field (hint / tooltip with example).
2) I would prefer to have the field pre-populated for me with all modules.

The idea to have to do as little configuration as possible to have the plugin working.
But also enabling the user to change the configuration for something more specific if required.

Let me know what you think.
Thank you very much.

Cheers,
Gui

**Comment by luismoramedina** [comment]
Hi again Gui,

Thanks for your reply.

1) Sorry, i miss the other fields tooltip :-( Something like that could work? "Eg: MyWebapp1 (Accepts multiple values) [Optional - CSV] If empty, the plugin use all modules to create the classpath"
2) If you pre-populate all modules and later you add another module to the intellij project you must update all configurations with this new module, this can be tricky. Another option is to have an empty value for an all-modules configuration. This way the user by default has the old behavieur. Another option is a combo, like intellij does...
image

Regards.

**Comment by guikeller** [comment]
Hi Luis,

I really like the combo box idea!

What about the following:
By default it should come with "All Modules" pre-selected - which is the default now.
Optionally, the plugin user could select one of the options from the combo box.

Thanks for your interest in helping and participating on the project.

Kind regards,
Gui

**Comment by luismoramedina** [comment]
Perfect! I´ll put you a message here when the change is ready.

Regards.

**Comment by guikeller** [comment]
Hi @luismoramedina 

That all sounds great! Again, thanks a lot for your collaboration.
I will close this pull request then; you can open a new one when you're ready. 

Cheers,
Gui

**Pull request closed without merging**
